CREATE TABLE EMPLOYEE (
  EMP_ID              VARCHAR(40)  NOT NULL,
  FIRST_NAME          VARCHAR(150) NOT NULL,
  PATERNAL_SURNAME    VARCHAR(50)  NOT NULL,
  MATERNAL_SURNAME    VARCHAR(50)  NOT NULL,
  BIRTHDAY            DATE         NULL,
  DEPARTMENT          INTEGER      NULL,
  ROL                 INTEGER      NULL,
  STATUS              BOOLEAN      NOT NULL
);